/**
 * File and folder icon packs.
 *
 * Each pack is a set of SVGs plus a manifest of name lookups, both generated by
 * `scripts/sync-*.mjs` into the renderer's public directory and `lib/`. The
 * generated files are gitignored, so `npm run icons` has to run before a build —
 * `predev` and `pretypecheck` take care of that.
 */
import materialManifest from './material-icons.json'
import catppuccinManifest from './catppuccin-icons.json'

/** Shape both generated manifests share, following VS Code icon theme files. */
export interface IconPackManifest {
  /** Icon for a file with no better match. */
  file: string
  folder: string
  folderExpanded: string
  /** Exact file names, lower-cased. */
  fileNames: Record<string, string>
  /** Extensions without the dot; the longest match wins. */
  fileExtensions: Record<string, string>
  folderNames: Record<string, string>
  folderNamesExpanded: Record<string, string>
}

export interface IconPack {
  id: string
  /** Shown in Settings. */
  name: string
  /** Directory under `public/` holding the SVGs. */
  dir: string
  manifest: IconPackManifest
}

export const ICON_PACKS: IconPack[] = [
  {
    id: 'material',
    name: 'Material Icons',
    dir: 'material-icons',
    manifest: materialManifest as IconPackManifest
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin Icons',
    dir: 'catppuccin-icons',
    manifest: catppuccinManifest as IconPackManifest
  }
]

export const DEFAULT_ICON_PACK = 'material'

const BY_ID = new Map(ICON_PACKS.map((pack) => [pack.id, pack]))

export function findIconPack(id: string): IconPack {
  return BY_ID.get(id) ?? (ICON_PACKS[0] as IconPack)
}

/** Icon definition for a file, following the pack's own lookups. */
function fileDefinition(pack: IconPack, fileName: string): string {
  const { manifest } = pack
  const lower = fileName.toLowerCase()

  const exact = manifest.fileNames[lower]
  if (exact) return exact

  // Match the longest extension chain first ("d.ts" before "ts").
  const parts = lower.split('.')
  for (let index = 1; index < parts.length; index += 1) {
    const hit = manifest.fileExtensions[parts.slice(index).join('.')]
    if (hit) return hit
  }

  return manifest.file
}

/** Icon definition for a folder, expanded or collapsed. */
function folderDefinition(pack: IconPack, folderName: string, expanded: boolean): string {
  const { manifest } = pack
  const named = expanded ? manifest.folderNamesExpanded : manifest.folderNames
  const lower = folderName.toLowerCase()
  return named[lower] ?? (expanded ? manifest.folderExpanded : manifest.folder)
}

/**
 * URL for an icon, resolved relative to the document so it works both on the
 * dev server and under the `file://` protocol in a packaged build.
 */
function definitionUrl(pack: IconPack, name: string): string {
  return new URL(`${pack.dir}/${name}.svg`, document.baseURI).href
}

/** URL of the icon for a file. */
export function fileIconUrl(packId: string, fileName: string): string {
  const pack = findIconPack(packId)
  return definitionUrl(pack, fileDefinition(pack, fileName))
}

/** URL of the icon for a folder. */
export function folderIconUrl(packId: string, folderName: string, expanded: boolean): string {
  const pack = findIconPack(packId)
  return definitionUrl(pack, folderDefinition(pack, folderName, expanded))
}
